// <auto-generated />
namespace Mishavad_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogPostFootNote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogPostFootNote));
        
        string IMigrationMetadata.Id
        {
            get { return "201612290549046_BlogPostFootNote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
