// <auto-generated />
namespace Mishavad_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FSTMinorFixAccNum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FSTMinorFixAccNum));
        
        string IMigrationMetadata.Id
        {
            get { return "201611051118272_FSTMinorFixAccNum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
